version: '3.7'
services:
  database:
    image: amazon/dynamodb-local:1.21.0
    restart: unless-stopped
    container_name: avascan.database
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    user: root
    environment:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_SESSION_TOKEN=""
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
  transactions-api:
    container_name: avascan.transactions-api
    volumes:
      - ./transactions-api/config:/app/config
      - ./transactions-api/src:/app/src
      - ./transactions-api/__tests__:/app/__tests__
      - ./transactions-api/__mocks__:/app/__mocks__
    image: avascan.transactions-api
    entrypoint: sh /app/dev.entrypoint.sh
    build:
      context: ./transactions-api
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file: .env.dev
    environment:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_SESSION_TOKEN=""
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    restart: unless-stopped