RESET_ENVIRONMENT: RESET_ENVIRONMENT
ENABLE_BATCH_INDEXER: ENABLE_BATCH_INDEXER
INITIAL_OLD_BLOCKS: INITIAL_OLD_BLOCKS
LOG_LEVEL: LOG_LEVEL
AVAX_RPC_NETWORK: AVAX_RPC_NETWORK
CALL_INTERVAL_IN_SECONDS: CALL_INTERVAL_IN_SECONDS
AWS_DEFAULT_REGION: AWS_DEFAULT_REGION
AWS_ENDPOINT: AWS_ENDPOINT
MAX_BLOCKS_TO_CHECK: MAX_BLOCKS_TO_CHECK