TRX_TABLE_NAME: Transaction
ADDRESS_TABLE_NAME: Address
MAX_BLOCKS_TO_CHECK: 25
RESET_ENVIRONMENT: true
ENABLE_BATCH_INDEXER: true
INITIAL_OLD_BLOCKS: 1
LOG_LEVEL: debug
CALL_INTERVAL_IN_SECONDS: 10
AVAX_RPC_NETWORK: https://mock.network
AWS_ENDPOINT: http://mocked.database
AWS_DEFAULT_REGION: us-east-1